export enum LeaderboardType {

  POKEMON = "POKEMON",

  COURSE = "COURSE",

  CHALLENGE = "CHALLENGE",

  REPORT_SCORE = "REPORT SCORE",

  SITE_COURSE_SCORE = "SITE COURSE SCORE",

  SITE_REPORT_SCORE = "SITE REPORT SCORE",

  TIME_ATTACK = "TIME ATTACK"

}
